name: Our Workflow
on: push
jobs:
   checkout:
       runs-on: ubuntu-latest
       steps:
        - run: ls -al
        - uses: actions/checkout@v4
        - run: ls -la
        - run: cat .github/workflows/checkout.yml
  
